[package]
name = "vtr-player"
version = "0.1.0"
edition = "2024"

[dependencies]
vtr-core = { path = "../vtr-core" }
anyhow = { workspace = true }
clap = { workspace = true }
rosc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3.27.0"
